name: Gradr

on:
  push:
    branches:
    - main

jobs:    
  autograde:
    name: Auto-Grade Submission
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Prepare Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Load Audits
      uses: actions/checkout@v2
      with: 
        repository: exam-01-practice/assignment-02-gradr-audits-js
        path: audits

    - name: Prepare Audits
      run: |
        npm install --location=global yarn
        cd audits
        yarn install

    - name: Review Challenge - 1
      run: |
        cd audits
        yarn audit-ch-1

    - name: Review Challenge - 2
      run: |
        cd audits
        yarn audit-ch-2

    - name: Review Challenge - 3
      run: |
        cd audits
        yarn audit-ch-3

    - name: Report Audits
      uses: exam-01-practice/jest-to-sheets@v1
      with:
        challenge: 'ch-1;ch-2;ch-3'
        lang: javascript
        server: https://api.sheetson.com/v2/sheets
        sheetid: 1Qb5Ovjy1l2UG94Cht2govguYX5fpCIgoTKPUd2ufMm4
        token: HXlur8K20ZpoB-6FNsnSUtj2kGoDqCDHDl8vZBdLtQCv9UFOVhMsM2IBwD8
        